services:
  backend:
    build: server/
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: "trello"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
    - ./database:/var/lib/postgresql